### PR TITLE
Types default values handeling cleanup

### PR DESCRIPTION
**Pull request by acatton**
Hello,

I went over all default the types in `cdist/types/` and I removed relics from when default types didn't exist.

I just replaced the pattern:
```bash
if [ -f "$__object/parameter/NAME" ]
then
   NAME="$(cat "$__object/parameter/NAME")"
else
   NAME="DEFAULT_VALUE"
fi
```

By:
```bash
NAME="$(cat "$__object/parameter/NAME")"
```
and putting `DEFAULT_VALUE` in `parameter/default/NAME`.

### CODE REVIEW

**Comment by telmich** [comment]
Awesome! I wanted to do this for months!

**Comment by acatton** [comment]
@telmich is there any plan to merge this?

Thanks.

**Comment by telmich** [comment]
Absolutely - sorry, it went out of sight

**Comment by acatton** [comment]
No problem @telmich, thank you for merging.

**Pull request merged**
